

def cond_opt(condominio_usuario):

    if condominio_usuario == "1": return "Reserva Sul Resort"
    elif condominio_usuario == "2": return "Jardim Paulista"
    elif condominio_usuario == "3": return "Edificio Damasco"
    elif condominio_usuario == "4": return "Edificio Ecoville"
    elif condominio_usuario == "5": return "Edificio Alleanza D'oro"
    elif condominio_usuario == "6": return "Edificio Figueira"
    elif condominio_usuario == "7": return "Edificio Itaporai"
    elif condominio_usuario == "8": return "Edificio Marcela e Monica"
    elif condominio_usuario == "9": return "Edificio Oliveira"
    elif condominio_usuario == "10": return "Haras Country Village"
    elif condominio_usuario == "11": return "Edificio Prime Office"
    elif condominio_usuario == "12": return "Portal dos Pinheiros"
    elif condominio_usuario == "13": return "Recreio Panorama"
    elif condominio_usuario == "14": return "Recreio Humaita "
    elif condominio_usuario == "15": return "Valencia Turia"
    elif condominio_usuario == "16": return "Santa Angela"
    elif condominio_usuario == "17": return "Santa Helena"
    elif condominio_usuario == "18": return "Santa Monica 1"
    elif condominio_usuario == "19": return "Santa Monica 2"
    elif condominio_usuario == "20": return "Villa Florença"
    elif condominio_usuario == "21": return "Vivendas do Sul"